# Site
repository: trangtoan293/toantt.github.io

# Content configuration version
version: 2

# Personal info
name: Thanh-Toan TRANG
title: Data Engineer
email: trangtoan293@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: trangtoan293
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: thanh-toan-t-aa32651ba
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Having served as the Data Engineering Lead at Katalyst Vietnam JSC for a year, I've gained deep insights into datamodelling and advanced data process development. My strong foundation in the fi nance sector is supported by aMaster's degree in European and International Private Banking from IAE Nice. This background enabled me to successfully design and implement an end-to-end DataVault Platform for one ofVietnam's premier banks, integrating the Data Vault Model and Data Transformation patterns on a Big Data Platform. I'm now eager to explore opportunities that will further develop my technical capabilities and allow me to work in aninternational environment, where I can harness new technologies to create innovative solutions.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Katalyst VietNam Company
        link: katalyst.vn
        # link_text: boringcompany.com
        sub_title: Data Engineering Lead
        caption: Oct 2022 - Present
        quote: >
          Design data platform
        description: | 
            - Architect and implement a comprehensive modern data platform for the company
            - Design Data Vault 2.0 modeling pattern to build a data warehouse.
            - Develop end-to-end data workfl ows on the data platform, including develop datapipeline, data catalog, data lineage, data quality and monitoring.
            - Design maintaining jobs, including small-fi les handling, snapshots expiring andremoving old metadata fi les.
            - Optimize Spark jobs to enhance data processing performance and minimizeresource utilization.
            - Design and develop DataVault Automation Tool to enhance the implementationprocess.
            - Co-operate with CTO to defi ne tools and services for the product.
      
      - layout: left
        title: Home Credit Vietnam Financial Company
        link: homecredit.vn
        # link_text: boringcompany.com
        sub_title: Business Intelligence Lead
        caption: Dec 2019 - Oct 2022
        quote: >
          Inhouse Data Platform Implementation
        description: | # this will include new lines to allow paragraphs
            - Report Automation: Spearheaded the generation of daily, monthly, and quarterlyautomated reports tailored for the Finance Department.
            - Dashboard Maintenance: Diligently maintained and updated the Board ofDirectors' Finance dashboards, ensuring accuracy and relevancy.
            - Regulatory & Tax Reporting: Enhanced and automated regulatory and taxreporting processes, with meticulous data mapping and monitoring to guaranteeSBV reporting compliance.
            - Data Integrity & Alerts: Instituted rigorous data quality checks, along with earlywarning systems and alerts for critical issues.
            - Data Reconciliation & Automation: Automated reconciliations between diversedata sources and streamlined the integration with the SAP Auto-booking process.
            - IT Collaboration & Data Strategy: Partnered with IT to fi ne-tune data strategy,emphasizing the roles of DWH, DataMart, and Hadoop. Promoted the use ofHadoop for enhanced reporting, positioning it as a reliable backup solution.
            - Support for Transformation Initiatives: Actively supported company transformationprojects, collaborating with the Accounting department to deliver essentialregulatory components.
     
      - layout: left
        title: HC Collection Agency Company
        link: --
        # link_text: boringcompany.com
        sub_title: Data Engineer
        caption: Jan 2021 - Present
        quote: >
          Evaluate collection team performance
        description: | # this will include new lines to allow paragraphs
          - Building a small-scale data platform for a company
          - Process and integrate data using ETL processes to ensure accuracy andconsistency by using Python and dbt.
          - Design a data storage and visualization tool, such as Metabase, for creating anoperator performance and Payment dashboard for the company.
          - Collect and analyze key performance metrics from collection team for reporting.
          - Enhance campaign approach to improve operator process.

      - layout: left
        title: Shinhan Bank Vietnam
        link: shinhan.com.vn
        # link_text: boringcompany.com
        sub_title: Data Analyst
        caption: Jun 2017 - Nov 2019
        quote: >
          Data Analytics and Management Credit Assessment
        description: | # this will include new lines to allow paragraphs
          - Generating daily/monthly or ad-hoc management reports to managers anddirectors.
          - Closely tracking on resource and capacity planning.
          - Developing effi cient scripting to manage data gathering, mining andtransformation.
          - Monitoring analytics and metrics results and delivering data-driven insight intoemerging problems, trends as required.
          - Collaborate with Assessment/Draw-down/Collection departments to identifybusiness process improvements.
  
  - title: Education # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        - <h4>Sep 2014 - Sep 2016 </h4>
          <h4>Master of European and International Private Banking </h4>
          <h5>IAE Nice - Université Côte d'Azur- FRANCE </h5>

        - <h4>Sep 2011 - Sep 2014 </h4>
          <h4>Bachelor of Economics and Management</h4>
          <h5>Toulouse 1 University Capitole - FRANCE </h5>
          

  - title: Certifications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
          - Apr 2024 [AWS Certified Cloud Practitioner](https://bit.ly/3vV8jpZ)
          - Mar 2023 [Data Vault 2.0 Practitioner](https://bit.ly/3UobAYa)

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Programming Languages: Python
      - Big Data Technologies: Hadoop Ecosystem, Apache Spark, YARN, Apache Kafka
      - Open Format Table: Apache Iceberg
      - Storage: MinIO
      - Streaming platform : Confluent
      - Database Management: Oracle, PostgreSQL
      - Transformation tool: dbt
      - Orchestration: Apache Airflow
      - Version Control: Git
      - Data Modeling: Ralph Kimball, Data Vault 2.0
      - Team Collaboration and Communication

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
